import fs from "node:fs"
import path from "node:path"
import { request } from "../api.js"
import { getRegistryUrl, getToken } from "../config.js"
import { createSpinner, log, printHeader } from "../ui.js"

/**
 * Generate a read-only .npmrc token for local development.
 * Creates a 30-day scoped token and writes it to the project's .npmrc.
 * Also ensures .npmrc is in .gitignore to prevent accidental commits.
 */
export async function npmrc(options) {
	printHeader()

	const token = await getToken()
	if (!token) {
		log.error(
			'You must be logged in to generate an .npmrc token. Run "lpm login" first.',
		)
		process.exit(1)
	}

	const projectRoot = process.cwd()
	const npmrcPath = path.join(projectRoot, ".npmrc")
	const gitignorePath = path.join(projectRoot, ".gitignore")

	// Check for package.json
	const pkgJsonPath = path.join(projectRoot, "package.json")
	if (!fs.existsSync(pkgJsonPath)) {
		log.warn("No package.json found. Run this command in your project root.")
	}

	// Derive project name for the token label
	let projectName = "project"
	if (fs.existsSync(pkgJsonPath)) {
		try {
			const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, "utf8"))
			if (pkg.name) {
				projectName = pkg.name.replace(/[^a-zA-Z0-9._-]/g, "-")
			}
		} catch {
			// Invalid package.json — use default name
		}
	}

	const expiryDays = parseInt(options?.days, 10) || 30
	const spinner = createSpinner("Creating read-only token...").start()

	// Call server to create a scoped read-only token
	let readToken
	let expiresAt
	try {
		const tokenName = `npmrc-${projectName}-${new Date().toISOString().slice(0, 10)}`
		const response = await request("/-/token/create", {
			method: "POST",
			body: JSON.stringify({
				scope: "read",
				name: tokenName,
				expiryDays,
			}),
			headers: { "Content-Type": "application/json" },
		})

		if (!response.ok) {
			const text = await response.text()
			throw new Error(`Token creation failed: ${response.status} ${text}`)
		}

		const data = await response.json()
		readToken = data.token
		expiresAt = data.expiresAt
		spinner.succeed("Read-only token created.")
	} catch (error) {
		spinner.fail(`Failed to create token: ${error.message}`)
		process.exit(1)
	}

	// Build .npmrc content
	const registryUrl = getRegistryUrl()
	const fullRegistryUrl = registryUrl.endsWith("/api/registry")
		? registryUrl
		: `${registryUrl}/api/registry`
	const registryHost = fullRegistryUrl.replace(/^https?:/, "")

	// Default: scoped (only @lpm.dev packages through lpm.dev).
	// --proxy: route all npm traffic through lpm.dev (Pro/Org feature).
	let useScoped = !options?.proxy

	// Read existing .npmrc and check for custom default registry
	let npmrcContent = ""
	if (fs.existsSync(npmrcPath)) {
		const existingContent = fs.readFileSync(npmrcPath, "utf8")

		// Detect custom default registry (not npmjs.org and not lpm.dev)
		if (!useScoped) {
			const registryLine = existingContent
				.split("\n")
				.find(
					line =>
						line.match(/^registry=/) &&
						!line.includes("registry.npmjs.org") &&
						!line.includes("lpm.dev"),
				)
			if (registryLine) {
				log.warn(`Found existing default registry: ${registryLine.trim()}`)
				log.warn("Using --scoped mode to avoid overriding it.")
				log.warn(
					"To use LPM as your default registry, remove the existing registry= line first.",
				)
				useScoped = true
			}
		}

		// Remove old LPM config lines (both scoped and unscoped formats)
		npmrcContent = existingContent
			.split("\n")
			.filter(line => {
				return (
					!line.includes("@lpm.dev:registry") &&
					!line.match(/^registry=.*lpm\.dev/) &&
					!line.includes("lpm.dev/api/registry/:_authToken") &&
					!line.includes("_authToken=lpm_") &&
					// biome-ignore lint/suspicious/noTemplateCurlyInString: matching literal npm token placeholder
					!line.includes("_authToken=${LPM_TOKEN}") &&
					!line.includes("# LPM Registry")
				)
			})
			.join("\n")
			.trim()
	}

	const registryLine = useScoped
		? `@lpm.dev:registry=${fullRegistryUrl}`
		: `registry=${fullRegistryUrl}`

	const lpmConfig = `# LPM Registry (generated by lpm npmrc — do not commit)
${registryLine}
${registryHost}/:_authToken=${readToken}`

	npmrcContent = npmrcContent ? `${npmrcContent}\n\n${lpmConfig}` : lpmConfig
	fs.writeFileSync(npmrcPath, `${npmrcContent}\n`)

	// Ensure .npmrc is in .gitignore
	let gitignoreUpdated = false
	if (fs.existsSync(gitignorePath)) {
		const gitignore = fs.readFileSync(gitignorePath, "utf8")
		if (!gitignore.split("\n").some(line => line.trim() === ".npmrc")) {
			fs.writeFileSync(gitignorePath, `${gitignore.trimEnd()}\n.npmrc\n`)
			gitignoreUpdated = true
		}
	} else {
		fs.writeFileSync(gitignorePath, ".npmrc\n")
		gitignoreUpdated = true
	}

	// Output
	console.log("")
	log.success(".npmrc configured with read-only LPM token.")
	if (gitignoreUpdated) {
		log.info(".npmrc added to .gitignore to prevent token leaks.")
	}

	if (useScoped) {
		log.info("Only @lpm.dev packages will route through lpm.dev.")
	} else {
		log.info("All packages (LPM + npm) will route through lpm.dev.")
		log.info("Note: First install may update resolved URLs in your lockfile.")
	}

	const expiryDate = new Date(expiresAt).toLocaleDateString("en-US", {
		year: "numeric",
		month: "long",
		day: "numeric",
	})
	log.info(`Token expires: ${expiryDate}`)
	log.info("Run `lpm npmrc` again to refresh when expired.")
	console.log("")
}
